image: Visual Studio 2019

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  BOOST_ROOT: C:/Libraries/boost_1_73_0
  DEKEN_PASSWORD:
    secure: J57LV7zrVl8xsXC/ng0TgA==
  GPG_DECODE_KEY:
    secure: wQW1TCaei6kT6u2A4fTmANYMSYghDGxnqaBRBcW0/QWxKNdmhAQymYC2srDrLi29I5U1bKoC6fZ9cHWsdNSE5w==

  matrix:
    - APPVEYOR_BUILD_TYPE: testing
      platform: x64
      configuration: Debug
      QTDIR: C:\Qt\latest\msvc2019_64

    - APPVEYOR_BUILD_TYPE: testing
      platform: x64
      configuration: Release
      QTDIR: C:\Qt\latest\msvc2019_64

    - APPVEYOR_BUILD_TYPE: Release
      configuration: Release
      QTDIR: C:\Qt\latest\msvc2019_64
      QTDIR-32bit: C:\Qt\latest\msvc2019

    - APPVEYOR_BUILD_TYPE: ossia-cpp
      configuration: Release

    - APPVEYOR_BUILD_TYPE: pd
      configuration: Release

    - APPVEYOR_BUILD_TYPE: pd-32bit
      configuration: Release

    #- APPVEYOR_BUILD_TYPE: purrdata
    #  configuration: Release

    #- APPVEYOR_BUILD_TYPE: purrdata-32bit
    #  configuration: Release

#    - APPVEYOR_BUILD_TYPE: pd-test
#      configuration: Debug
#      QTDIR-32bit: C:\Qt\latest\msvc2019

    - APPVEYOR_BUILD_TYPE: max
      configuration: Release

#     - APPVEYOR_BUILD_TYPE: python
#       configuration: Release
#       python: Python27
#       platform: x64
# 
#     - APPVEYOR_BUILD_TYPE: python
#       configuration: Release
#       python: Python27
#       platform: x86
# 
#     - APPVEYOR_BUILD_TYPE: python
#       configuration: Release
#       python: Python36
#       platform: x64
# 
#     - APPVEYOR_BUILD_TYPE: python
#       configuration: Release
#       python: Python36
#       platform: x86
# 
    - APPVEYOR_BUILD_TYPE: qml
      configuration: Release
      QTDIR: C:\Qt\latest\msvc2019_64
      QTDIR-32bit: C:\Qt\latest\msvc2019
      platform: x64

before_build:
  - ps: C:\projects\libossia\ci\before_build.ps1

build_script:
  - ps: C:\projects\libossia\ci\build.ps1

after_build:
  - ps: C:\projects\libossia\ci\after_build.ps1

test_script:
  - ps: C:\projects\libossia\ci\test.ps1

artifacts:
  - path: ossia-pd-win32.zip
    name: ossia-pd-win32
    type: zip
  - path: ossia-pd-win64.zip
    name: ossia-pd-win64
    type: zip
  - path: ossia-purrdata-win32.zip
    name: ossia-purrdata-win32
    type: zip
  - path: ossia-purrdata-win64.zip
    name: ossia-purrdata-win64
    type: zip
  - path: ossia-max-win.zip
    name: ossia-max-win
    type: zip
  - path: ossia-qml-win64.zip
    name: ossia-qml-win64
    type: zip
  - path: ossia-cpp-win.zip
    name: ossia-cpp-win
    type: zip
  - path: libossia-native-win*.zip
    name: ossia-windows
    type: zip
#  - path: pyossia*.whl
#    name: pyossia-wheel-win
#    type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: Zl/uqZozGXtvixbEP89fyT3oQW6uKclpRGOa1Rwsdryt7zrGk0pQBRXUwUSzNrA2
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
