name: 'Install RPi toolchain'
description: 'Install RPi toolchain'
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -yqq 
        sudo apt-get upgrade -yqq
        sudo apt-get install -yqq build-essential ninja-build libavahi-client-dev wget

        wget -nv https://github.com/tttapa/docker-arm-cross-toolchain/releases/download/0.1.2/x-tools-aarch64-rpi3-linux-gnu.tar.xz
        tar xaf x-tools-aarch64-rpi3-linux-gnu.tar.xz
        sudo mv x-tools/aarch64-rpi3-linux-gnu /opt/cross-pi-gcc
