name: 'Install Mac toolchain'
description: 'Install Mac toolchain'
runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      if: runner.os == 'macOS'
      with:
        xcode-version: latest-stable

    - name: Install Dependencies
      run: brew install ninja
      shell: bash