name: 'Notarize and codesign'
description: 'Notarize and codesign'

inputs:
  path-to-sign:
    description: 'Path containing files to sign'
    required: true
    default: ''
  output-name:
    description: 'Output filename'
    required: true
    default: 'output.zip'
  MAC_CERT_B64:
    description: 'Certificate encoded as base64'
    required: true
    default: ''
  MAC_CERT_PASSWORD:
    description: 'Certificate password'
    required: true
    default: ''
  MAC_ALTOOL_PASSWORD:
    description: 'macOS notarization password'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Code Signing
      shell: bash
      env:
        MAC_CERT_B64: ${{ inputs.MAC_CERT_B64 }}
        MAC_CERT_PASSWORD: ${{ inputs.MAC_CERT_PASSWORD }}
        MAC_ALTOOL_PASSWORD: ${{ inputs.MAC_ALTOOL_PASSWORD }}
      run: |
        source "${GITHUB_WORKSPACE}/ci/codesign_functions.sh"
        release_macos_folder "${{ inputs.path-to-sign }}" "$PWD/${{ inputs.output-name }}"
